serviceTree:
  landscape: entei
  cluster: amber
  platform: sulfoxide
  service: carbon
  layer: "1"

revisionLimit: 3
projectName: bootstrap
destination: ""

enableAppSet: "true"
virtualClusters: {}
#  pichu:
#    apiServerBaseDomain: kubernetes.atomi.cloud
#    refreshInterval: 1m
#    policy:
#      creation: Owner
#      deletion: Retain
#  pikachu:
#    apiServerBaseDomain: kubernetes.atomi.cloud
#    refreshInterval: 1m
#    policy:
#      creation: Owner
#      deletion: Retain
#  raichu:
#    apiServerBaseDomain: kubernetes.atomi.cloud
#    refreshInterval: 1m
#    policy:
#      creation: Owner
#      deletion: Retain

apps:
  prometheus:
    sync: 0
    deploy: true
    values: [ "values.yaml" ]

  # Karpenter, Cluster Autoscaler, Krypton
  krypton:
    sync: 0
    deploy: true
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # External Secrets, Secrets Engine, Cobalt
  cobalt:
    sync: 1
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # EKS Drivers, EKS Drivers, Lead
  lead:
    sync: 1
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Kyverno, Policy Engine, Argon
  argon:
    sync: 2
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Metric Server, Metrics, Xenon
  xenon:
    sync: 2
    namespace: sulfoxide
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Reloader, Reloader, Chlorine
  chlorine:
    sync: 2
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Cert Manager, Certificate Engine, Sulfur
  sulfur:
    sync: 2
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # External DNS, DNS Engine, Tin
  tin:
    sync: 2
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Kyverno Policies, Policies, Sodium
  sodium:
    sync: 3
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Cloudflared, Internal Ingress, Boron
  boron:
    sync: 3
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # KEDA, Pod Autoscaler, Iron
  iron:
    sync: 3
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # OTEL Operator, Observability Engine, Lithium
  lithium:
    sync: 3
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Cluster Issuer, Certificate Issuer, Zinc
  zinc:
    sync: 3
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # OTEL Collectors, Observability Agents, Silicon
  silicon:
    sync: 4
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # Nginx, External Ingress, Gold
  gold:
    sync: 4
    deploy: false
    values: [ "values.yaml", "values.entei.amber.yaml" ]

  # pichu vcluster, Pichu Virtual Cluster, Pichu Iodine
  pichu-iodine:
    sync: 5
    deploy: false
    values: [ "values.yaml", "values.pichu.amber.yaml" ]
    createNamespace: true

  # pikachu vcluster, Pikachu Virtual Cluster, Pikachu Iodine
  pikachu-iodine:
    sync: 5
    deploy: false
    values: [ "values.yaml", "values.pikachu.amber.yaml" ]
    createNamespace: true

  # raichu vcluster, Raichu Virtual Cluster, Raichu Iodine
  raichu-iodine:
    sync: 5
    deploy: false
    values: [ "values.yaml", "values.raichu.amber.yaml" ]
    createNamespace: true

  # pichu vcluster bootstrap, Pichu Virtual Cluster Bootstrap, Pichu Carbon
  pichu-carbon:
    sync: 6
    deploy: false
    values: [ "values.yaml", "values.pichu.amber.yaml" ]

  # pichu vcluster bootstrap, Pichu Virtual Cluster Bootstrap, Pichu Carbon
  pikachu-carbon:
    sync: 6
    deploy: false
    values: [ "values.yaml", "values.pikachu.amber.yaml" ]

  # pichu vcluster bootstrap, Pichu Virtual Cluster Bootstrap, Pichu Carbon
  raichu-carbon:
    sync: 6
    deploy: false
    values: [ "values.yaml", "values.raichu.amber.yaml" ]
