serviceTree:
  landscape: pichu
  platform: systems
  service: bootstrap
  layer: "1"

revisionLimit: 3
projectName: default
destination: https://d1943bf9-8108-45d0-a666-9782e2e848c7.vultr-k8s.com:6443

apps:
  prometheus:
    sync: 0
    deploy: true
    release: prometheus-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.0.0
    values: [ "values.yaml" ]
    namespace: default
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false
    chart: prometheus-operator-crds

  kyverno:
    sync: 1
    deploy: true
    release: pichu-kyverno
    repo: https://github.com/AtomiCloud/helm.systems_kyverno
    version: HEAD
    path: "chart"
    values: ["values.yaml", "values.pichu.yaml"]
    namespace: policy-engine
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: true

  policies:
    sync: 2
    deploy: false
    release: kyverno-policies
    repo: https://github.com/AtomiCloud/helm.systems_kyverno-policies
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: policy-engine
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false

  metric-server:
    sync: 3
    deploy: false
    release: metric-server
    repo: https://github.com/AtomiCloud/helm.systems_metric-server
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: kube-system
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false
  reloader:
    sync: 3
    deploy: false
    release: reloader
    repo: https://github.com/AtomiCloud/helm.systems_reloader
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: reloader
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false

  cert-manager:
    sync: 3
    deploy: false
    release: cert-manager
    repo: https://github.com/AtomiCloud/helm.systems_cert-manager
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: cert-manager
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false

  otel:
    sync: 3
    deploy: false
    release: otel
    repo: https://github.com/AtomiCloud/helm.systems_otel-operator
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: otel
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false

  cloudflared:
    sync: 3
    deploy: false
    release: cloudflared
    repo: https://github.com/AtomiCloud/helm.systems_cloudflared
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: internal-ingress
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false

  keda:
    sync: 4
    deploy: false
    release: keda
    repo: https://github.com/AtomiCloud/helm.systems_keda
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: keda
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false

  cluster-issuer:
    sync: 4
    deploy: false
    release: cluster-issuer
    repo: https://github.com/AtomiCloud/helm.systems_cluster-issuer
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: cert-manager
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  otel-collectors:
    sync: 4
    deploy: false
    release: otel-collectors
    repo: https://github.com/AtomiCloud/helm.systems_otel-collectors
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: otel
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  kong:
    sync: 5
    deploy: false
    release: kong
    repo: https://github.com/AtomiCloud/helm.systems_kong-ingress
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: external-ingress
    createNamespace: true
    pruneLast: true
    replace: false
    serverSideApply: false