# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  landscape: pichu
  cluster: opal
  platform: sulfoxide
  service: carbon
  layer: "1"

revisionLimit: 3
projectName: default
destination: https://d1943bf9-8108-45d0-a666-9782e2e848c7.vultr-k8s.com:6443

apps:
  prometheus:
    sync: 0
    deploy: true
    release: prometheus-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.0.0
    values: [ "values.yaml" ]
    namespace: default
    createNamespace: false
    pruneLast: true
    replace: true
    serverSideApply: true
    chart: prometheus-operator-crds

  kyverno:
    sync: 1
    deploy: false
    release: argon
    repo: https://github.com/AtomiCloud/sulfoxide.argon
    version: HEAD
    path: "chart"
    values: ["values.yaml" ]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: true

  policies:
    sync: 2
    deploy: false
    release: sodium
    repo: https://github.com/AtomiCloud/sulfoxide.sodium
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  metric-server:
    sync: 3
    deploy: false
    release: xenon
    repo: https://github.com/AtomiCloud/sulfoxide.xenon
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: kube-system
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  reloader:
    sync: 3
    deploy: false
    release: chlorine
    repo: https://github.com/AtomiCloud/sulfoxide.chlorine
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  cert-manager:
    sync: 3
    deploy: false
    release: sulfur
    repo: https://github.com/AtomiCloud/sulfoxide.sulfur
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  otel-operator:
    sync: 3
    deploy: false
    release: lithium
    repo: https://github.com/AtomiCloud/sulfoxide.lithium
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  secrets-engine:
    sync: 3
    deploy: false
    release: cobalt
    repo: https://github.com/AtomiCloud/sulfoxide.cobalt
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  external-dns:
    sync: 4
    deploy: false
    release: tin
    repo: https://github.com/AtomiCloud/sulfoxide.tin
    version: HEAD
    path: chart
    values: [ "values.yaml", "values.entei.opal.yaml" ]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  cloudflared:
    sync: 4
    deploy: false
    release: boron
    repo: https://github.com/AtomiCloud/sulfoxide.boron
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  keda:
    sync: 4
    deploy: false
    release: iron
    repo: https://github.com/AtomiCloud/sulfoxide.iron
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: true



  cluster-issuer:
    sync: 4
    deploy: false
    release: zinc
    repo: https://github.com/AtomiCloud/sulfoxide.zinc
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  otel-collectors:
    sync: 4
    deploy: false
    release: silicon
    repo: https://github.com/AtomiCloud/sulfoxide.silicon
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  nginx:
    sync: 5
    deploy: false
    release: gold
    repo: https://github.com/AtomiCloud/sulfoxide.gold
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  kong:
    sync: 5
    deploy: false
    release: oxygen
    repo: https://github.com/AtomiCloud/sulfoxide.oxygen
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  pichu-vcluster:
    sync: 6
    deploy: false
    release: pichu-iodine
    repo: https://github.com/AtomiCloud/sulfoxide.iodine
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: pichu
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false
  pikachu-vcluster:
    sync: 6
    deploy: false
    release: pikachu-iodine
    repo: https://github.com/AtomiCloud/sulfoxide.iodine
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: pikachu
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false
  raichu-vcluster:
    sync: 6
    deploy: false
    release: raichu-iodine
    repo: https://github.com/AtomiCloud/sulfoxide.iodine
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: raichu
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false