serviceTree:
  landscape: entei
  cluster: opal
  platform: sulfoxide
  service: carbon
  layer: "1"

revisionLimit: 3
projectName: default
destination: https://7c18dd8b-3d7a-43da-9ad6-b38c615781b0.k8s.ondigitalocean.com

virtualClusters: {}
#  pichu:
#    apiServerBaseDomain: kubernetes.cluster.atomi.cloud
#    refreshInterval: 1m
#    policy:
#      creation: Owner
#      deletion: Retain
#  pikachu:
#    apiServerBaseDomain: kubernetes.cluster.atomi.cloud
#    refreshInterval: 1m
#    policy:
#      creation: Owner
#      deletion: Retain
#  raichu:
#    apiServerBaseDomain: kubernetes.cluster.atomi.cloud
#    refreshInterval: 1m
#    policy:
#      creation: Owner
#      deletion: Retain

apps:
  prometheus:
    sync: 0
    deploy: true
    values: [ "values.yaml" ]
    namespace: sulfoxide
    createNamespace: true

  kyverno:
    deploy: false

  policies:
    deploy: false

  metric-server:
    sync: 1
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]
    namespace: kube-system
    createNamespace: false

  reloader:
    sync: 1
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]
    namespace: sulfoxide

  cert-manager:
    sync: 1
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]
    namespace: sulfoxide
    createNamespace: true

  otel-operator:
    sync: 1
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]
    namespace: sulfoxide

  external-dns:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.opal.yaml" ]
    namespace: sulfoxide
    createNamespace: true

  cloudflared:
    sync: 2
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]

  keda:
    deploy: false

  cluster-issuer:
    sync: 2
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]

  otel-collectors:
    deploy: false

  nginx:
    sync: 3
    deploy: false
    values: ["values.yaml", "values.entei.opal.yaml"]

  pichu-vcluster:
    sync: 4
    deploy: false
    release: pichu-iodine
    values: [ "values.yaml", "values.pichu.opal.yaml" ]
    createNamespace: true

  pikachu-vcluster:
    sync: 4
    deploy: false
    values: [ "values.yaml", "values.pikachu.opal.yaml" ]
    createNamespace: true

  raichu-vcluster:
    sync: 4
    deploy: false
    values: [ "values.yaml", "values.raichu.opal.yaml" ]
    createNamespace: true