serviceTree:
  landscape: entei
  cluster: ruby
  platform: sulfoxide
  service: carbon
  layer: "1"

revisionLimit: 3
projectName: bootstrap
destination: ""

enableAppSet: "true"
virtualClusters:
  pichu:
    apiServerBaseDomain: kubernetes.atomi.cloud
    refreshInterval: 1m
    policy:
      creation: Owner
      deletion: Retain
  pikachu:
    apiServerBaseDomain: kubernetes.atomi.cloud
    refreshInterval: 1m
    policy:
      creation: Owner
      deletion: Retain
  raichu:
    apiServerBaseDomain: kubernetes.atomi.cloud
    refreshInterval: 1m
    policy:
      creation: Owner
      deletion: Retain

apps:
  prometheus:
    sync: 0
    deploy: true
    values: [ "values.yaml" ]

  # External Secrets, Secrets Engine, Cobalt
  cobalt:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.opal.yaml" ]

  # Kyverno, Policy Engine, Argon
  argon:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Metric Server, Metrics, Xenon
  xenon:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Reloader, Reloader, Chlorine
  chlorine:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Cert Manager, Certificate Engine, Sulfur
  sulfur:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # External DNS, DNS Engine, Tin
  tin:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Kyverno Policies, Policies, Sodium
  sodium:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Cloudflared, Internal Ingress, Boron
  boron:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # KEDA, Pod Autoscaler, Iron
  iron:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # OTEL Operator, Observability Engine, Lithium
  lithium:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Cluster Issuer, Certificate Issuer, Zinc
  zinc:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # OTEL Collectors, Observability Agents, Silicon
  silicon:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]

  # Nginx, External Ingress, Gold
  gold:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.entei.ruby.yaml" ]


  # pichu vcluster, Pichu Virtual Cluster, Pichu Iodine
  pichu-iodine:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.pichu.ruby.yaml" ]
    createNamespace: true

  # pikachu vcluster, Pikachu Virtual Cluster, Pikachu Iodine
  pikachu-iodine:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.pikachu.ruby.yaml" ]
    createNamespace: true

  # raichu vcluster, Raichu Virtual Cluster, Raichu Iodine
  raichu-iodine:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.raichu.ruby.yaml" ]
    createNamespace: true

  # pichu vcluster bootstrap, Pichu Virtual Cluster Bootstrap, Pichu Carbon
  pichu-carbon:
    sync: 5
    deploy: true
    values: [ "values.yaml", "values.pichu.ruby.yaml" ]

  # pichu vcluster bootstrap, Pichu Virtual Cluster Bootstrap, Pichu Carbon
  pikachu-carbon:
    sync: 5
    deploy: true
    values: [ "values.yaml", "values.pikachu.ruby.yaml" ]

  # pichu vcluster bootstrap, Pichu Virtual Cluster Bootstrap, Pichu Carbon
  raichu-carbon:
    sync: 5
    deploy: true
    values: [ "values.yaml", "values.raichu.ruby.yaml" ]
