labels:
  landscape: pichu
  platform: systems
  service: bootstrap
  layer: "1"

revisionLimit: 3
projectName: default
destination: https://d1943bf9-8108-45d0-a666-9782e2e848c7.vultr-k8s.com:6443

apps:
  kyverno:
    sync: 0
    deploy: true
    release: kyverno
    repo: https://github.com/AtomiCloud/helm.systems_kyverno
    version: HEAD
    path: "chart"
    values: ["values.yaml", "values.pichu.yaml"]
    namespace: policy-engine
    createNamespace: true

  policies:
    sync: 1
    deploy: false
    release: kyverno-policies
    repo: https://github.com/tr8team/helm.systems_kyverno-policies
    version: HEAD
    path: "chart"
    values: ["values.yaml", "values.admin.yaml"]
    namespace: policy-engine
    createNamespace: true

  metricServer:
    sync: 2
    deploy: false
    release: metric-server
    repo: https://github.com/tr8team/helm.systems_metrics-server
    version: HEAD
    path: "chart"
    values: ["values.yaml", "values.admin.yaml"]
    namespace: kube-system
    createNamespace: true

  reloader:
    sync: 2
    deploy: false
    release: reloader
    repo: https://github.com/tr8team/helm.systems_reloader
    version: HEAD
    path: "chart"
    values: ["values.yaml", "values.admin.yaml"]
    namespace: reloader
    createNamespace: true

  certManager:
    sync: 2
    deploy: false
    release: cert-manager
    repo: https://github.com/tr8team/helm.systems_cert-manager
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: cert-manager
    createNamespace: true

  otel:
    sync: 2
    deploy: false
    release: otel
    repo: https://github.com/tr8team/helm.systems_otel
    version: HEAD
    path: chart
    values: ["values.yaml", "values.admin.yaml"]
    namespace: otel
    createNamespace: true

  cloudflared:
    sync: 2
    deploy: false
    release: cloudflared
    repo: https://github.com/tr8team/helm.systems_cloudflared
    version: HEAD
    path: chart
    values: ["values.yaml", "values.admin.yaml"]
    namespace: internal-ingress
    createNamespace: true

  keda:
    sync: 3
    deploy: false
    release: keda
    repo: https://github.com/tr8team/helm.systems_keda
    version: HEAD
    path: "chart"
    values: ["values.yaml", "values.admin.yaml"]
    namespace: keda
    createNamespace: true

  clusterIssuer:
    sync: 3
    deploy: false
    release: cluster-issuer
    repo: https://github.com/tr8team/helm.systems_cluster-issuer
    version: HEAD
    path: chart
    values: ["values.yaml", "values.admin.yaml"]
    namespace: cert-manager
    createNamespace: false

  otel-collectors:
    sync: 3
    deploy: false
    release: otel-collectors
    repo: https://github.com/tr8team/helm.systems_otel
    version: HEAD
    path: chart
    values: ["values.yaml", "values.admin.yaml"]
    namespace: otel
    createNamespace: false

  kong:
    sync: 4
    deploy: false
    release: kong
    repo: https://github.com/tr8team/helm.systems_kong-ingress
    version: HEAD
    path: chart
    values: ["values.yaml", "values.admin.yaml"]
    namespace: external-ingress
    createNamespace: true
