serviceTree:
  landscape: pichu
  cluster: opal

revisionLimit: 3
projectName: default
destination: https://kubernetes.api

virtualClusters: { }

apps:
  prometheus:
    sync: 0
    deploy: true
    values: [ "values.yaml" ]

  # [Argon] Policy Engine
  kyverno:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]
    namespace: sulfoxide
    createNamespace: true

  # [Sodium] Policies
  policies:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  metric-server:
    deploy: false

  reloader:
    deploy: false

  cert-manager:
    deploy: false

  otel-operator:
    deploy: false

  # [Cobalt] Secrets Enginer, External Secret
  secrets-engine:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  external-dns:
    deploy: false

  # [Iron] Pod Autoscaler
  keda:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # [Boron] Internal Ingress
  cloudflared:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  cluster-issuer:
    deploy: false
  otel-collectors:
    deploy: false
  nginx:
    deploy: false
  kong:
    deploy: false
  pichu-vcluster:
    deploy: false
  pikachu-vcluster:
    deploy: false
  raichu-vcluster:
    deploy: false
