serviceTree:
  landscape: pichu
  cluster: opal
  platform: systems
  service: bootstrap
  layer: "1"

revisionLimit: 3
projectName: bootstrap
destination: https://e31a3b7c-4ef1-48c5-a0b6-9dc32d781c3d.vultr-k8s.com:6443

apps:
  kyverno:
    deploy: false
    release: pichu-opal-kyverno
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  policies:
    deploy: false
    release: kyverno-policies
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  metric-server:
    deploy: false
    release: metric-server
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  reloader:
    deploy: false
    release: reloader
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  cert-manager:
    deploy: false
    release: cert-manager
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  otel:
    deploy: false
    release: otel
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  cloudflared:
    deploy: false
    release: cloudflared
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  keda:
    deploy: false
    release: keda
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  cluster-issuer:
    deploy: false
    release: cluster-issuer
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  otel-collectors:
    deploy: false
    release: otel-collectors
    version: HEAD
    values: ["values.yaml", "values.admin.yaml"]

  kong:
    deploy: false
    release: kong
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]
