# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  landscape: pichu
  cluster: opal
  platform: sulfoxide
  service: carbon
  layer: "1"

revisionLimit: 3
projectName: default
destination: https://kubernetes.api

virtualClusters: {}
#  pichu:
#    refreshInterval: 1m
#    store:
#      name: entei-opal
#      kind: ClusterStore
#    policy:
#      creation: Owner
#      deletion: Retain

apps:
  prometheus:
    sync: 0
    deploy: true
    release: prometheus-crds
    repo: https://prometheus-community.github.io/helm-charts
    version: 5.0.0
    values: [ "values.yaml" ]
    namespace: default
    createNamespace: false
    pruneLast: true
    replace: true
    serverSideApply: true
    chart: prometheus-operator-crds

  # Kyverno, Policy Engine, Argon
  argon:
    sync: 1
    deploy: false
    release: argon
    repo: https://github.com/AtomiCloud/sulfoxide.argon
    version: HEAD
    path: "chart"
    values: ["values.yaml" ]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: true

  # Kyverno Policies, Policies, Sodium
  sodium:
    sync: 2
    deploy: false
    release: sodium
    repo: https://github.com/AtomiCloud/sulfoxide.sodium
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # Metric Server, Metrics, Xenon
  xenon:
    sync: 3
    deploy: false
    release: xenon
    repo: https://github.com/AtomiCloud/sulfoxide.xenon
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: kube-system
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # Reloader, Reloader, Chlorine
  chlorine:
    sync: 3
    deploy: false
    release: chlorine
    repo: https://github.com/AtomiCloud/sulfoxide.chlorine
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # Cert Manager, Certificate Engine, Sulfur
  sulfur:
    sync: 3
    deploy: false
    release: sulfur
    repo: https://github.com/AtomiCloud/sulfoxide.sulfur
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # OTEL Operator, Observability Engine, Lithium
  lithium:
    sync: 3
    deploy: false
    release: lithium
    repo: https://github.com/AtomiCloud/sulfoxide.lithium
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # External Secrets, Secrets Engine, Cobalt
  cobalt:
    sync: 3
    deploy: false
    release: cobalt
    repo: https://github.com/AtomiCloud/sulfoxide.cobalt
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # External DNS, DNS Engine, Tin
  tin:
    sync: 4
    deploy: false
    release: tin
    repo: https://github.com/AtomiCloud/sulfoxide.tin
    version: HEAD
    path: chart
    values: [ "values.yaml", "values.entei.opal.yaml" ]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # Cloudflared, Internal Ingress, Boron
  boron:
    sync: 4
    deploy: false
    release: boron
    repo: https://github.com/AtomiCloud/sulfoxide.boron
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # KEDA, Pod Autoscaler, Iron
  iron:
    sync: 4
    deploy: false
    release: iron
    repo: https://github.com/AtomiCloud/sulfoxide.iron
    version: HEAD
    path: "chart"
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: true
    ignoreDifferences:
      - group: apiregistration.k8s.io
        kind: APIService
        namespace: sulfoxide
        jsonPointers:
          - /spec/insecureSkipTLSVerify

  # Cluster Issuer, Certificate Issuer, Zinc
  zinc:
    sync: 4
    deploy: false
    release: zinc
    repo: https://github.com/AtomiCloud/sulfoxide.zinc
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # OTEL Collectors, Observability Agents, Silicon
  silicon:
    sync: 4
    deploy: false
    release: silicon
    repo: https://github.com/AtomiCloud/sulfoxide.silicon
    version: HEAD
    path: chart
    values: ["values.yaml"]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # Nginx, External Ingress, Gold
  gold:
    sync: 5
    deploy: false
    release: gold
    repo: https://github.com/AtomiCloud/sulfoxide.gold
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: sulfoxide
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # pichu vcluster, Pichu Virtual Cluster, Pichu Iodine
  pichu-iodine:
    sync: 6
    deploy: false
    release: pichu-iodine
    repo: https://github.com/AtomiCloud/sulfoxide.iodine
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: pichu
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # pikachu vcluster, Pikachu Virtual Cluster, Pikachu Iodine
  pikachu-iodine:
    sync: 6
    deploy: false
    release: pikachu-iodine
    repo: https://github.com/AtomiCloud/sulfoxide.iodine
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: pikachu
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false

  # raichu vcluster, Raichu Virtual Cluster, Raichu Iodine
  raichu-iodine:
    sync: 6
    deploy: false
    release: raichu-iodine
    repo: https://github.com/AtomiCloud/sulfoxide.iodine
    version: HEAD
    path: chart
    values: [ "values.yaml" ]
    namespace: raichu
    createNamespace: false
    pruneLast: true
    replace: false
    serverSideApply: false