serviceTree:
  landscape: pichu
  cluster: opal
  platform: systems
  service: bootstrap
  layer: "1"

revisionLimit: 3
projectName: bootstrap
destination: https://b42a689b-73cf-4d73-ba8d-47f706754e83.k8s.ondigitalocean.com

apps:
  prometheus:
    deploy: true
    release: prometheus-crds
    version: 5.0.0
    values: [ "values.yaml" ]

  kyverno:
    deploy: true
    release: pichu-opal-kyverno
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  policies:
    deploy: true
    release: kyverno-policies
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  metric-server:
    deploy: true
    release: metric-server
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  reloader:
    deploy: true
    release: reloader
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  cert-manager:
    deploy: true
    release: cert-manager
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  otel:
    deploy: true
    release: otel
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  cloudflared:
    deploy: true
    release: cloudflared
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  keda:
    deploy: true
    release: keda
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  cluster-issuer:
    deploy: true
    release: cluster-issuer
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  otel-collectors:
    deploy: false
    release: otel-collectors
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]

  kong:
    deploy: true
    release: kong
    version: HEAD
    values: ["values.yaml", "values.pichu.opal.yaml"]
