serviceTree:
  landscape: pichu
  cluster: opal

revisionLimit: 3
projectName: bootstrap
destination: https://pichu.opal.kubernetes.cluster.atomi.cloud

virtualClusters: { }

apps:
  prometheus:
    deploy: false

  # Kyverno, Policy Engine, Argon
  argon:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # Kyverno Policies, Policies, Sodium
  sodium:
    sync: 2
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # Metric Server, Metrics, Xenon
  xenon:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # External Secrets, Secrets Engine, Cobalt
  cobalt:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # OTEL Operator, Observability Engine, Lithium
  lithium:
    sync: 3
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # OTEL Collectors, Observability Agents, Silicon
  silicon:
    sync: 4
    deploy: false
    values: [ "values.yaml", "values.pichu.opal.yaml" ]

  # KEDA, Pod Autoscaler, Iron
  iron:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.pichu.opal.yaml" ]