serviceTree:
  landscape: entei
  cluster: opal
  platform: sulfoxide
  service: carbon
  layer: "1"

revisionLimit: 3
projectName: default
destination: https://7c18dd8b-3d7a-43da-9ad6-b38c615781b0.k8s.ondigitalocean.com

virtualClusters:
  pichu:
    refreshInterval: 1m
    store:
      name: entei-opal
      kind: ClusterStore
    policy:
      creation: Owner
      deletion: Retain


apps:
  prometheus:
    sync: 0
    deploy: true
    values: [ "values.yaml" ]
    namespace: default

  kyverno:
    deploy: false

  policies:
    deploy: false

  metric-server:
    sync: 1
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]
    namespace: kube-system
    createNamespace: false

  reloader:
    deploy: false

  cert-manager:
    sync: 1
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]
    namespace: sulfoxide
    createNamespace: true

  otel-operator:
    deploy: false

  external-dns:
    sync: 1
    deploy: true
    values: [ "values.yaml", "values.entei.opal.yaml" ]
    namespace: sulfoxide
    createNamespace: true

  cloudflared:
    sync: 2
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]

  keda:
    deploy: false

  cluster-issuer:
    sync: 2
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]

  otel-collectors:
    deploy: false

  kong:
    sync: 3
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]

  nginx:
    sync: 3
    deploy: true
    values: ["values.yaml", "values.entei.opal.yaml"]

  pichu-vcluster:
    sync: 4
    deploy: true
    release: pichu-iodine
    values: [ "values.yaml", "values.pichu.opal.yaml" ]
    createNamespace: true

  pikachu-vcluster:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.pikachu.opal.yaml" ]
    createNamespace: true

  raichu-vcluster:
    sync: 4
    deploy: true
    values: [ "values.yaml", "values.raichu.opal.yaml" ]
    createNamespace: true