version: "3"

env:
  RELEASE_NAME: app-of-apps

includes:
  render: tasks/Taskfile.render.yaml

tasks:
  # Utility
  start:cluster:
    desc: Starts the playground cluster to test helm charts
    cmds:
      - ./scripts/local/create-k3d-cluster.sh

  stop:cluster:
    desc: Destroys the playground cluster to test helm charts
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh

  # Helm Operations
  add:helm:repo:
    desc: Add Helm dependency repositories
    dir: chart
    cmds:
      - yq --indent 0 '.dependencies | map(["helm", "repo", "add", .name, .repository] | join(" ")) | .[]' "Chart.lock" | sh --

  update:
    desc: Update Helm dependencies
    dir: chart
    cmds:
      - helm dependency update

  deps:
    desc: Install Helm dependencies
    dir: chart
    cmds:
      - task: add:helm:repo
      - helm dependency build

  debug:
    desc: Debug the helm chart
    cmds:
      - task: deps
      - helm template $RELEASE_NAME ./chart --debug {{.CLI_ARGS}}

  install:
    desc: Installs the chart
    cmds:
      - task: deps
      - helm upgrade --install $RELEASE_NAME ./chart {{.CLI_ARGS}}

  remove:
    desc: Removes an installed release
    cmds:
      - helm uninstall $RELEASE_NAME
