apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{.Values.projectName }}
  labels:
    {{- include "atomi-app-of-apps.labels" . | nindent 4 }}

  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    {{- include "atomi-app-of-apps.annotations" . | nindent 4 }}
spec:
  description: "Bootstrap Project used to setup the cluster"

  sourceRepos:
    - '*'

  destinations:
    - namespace: "*"
      server: "*"

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: false
