{{- range $k, $v := .Values.virtualClusters }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $k }}-cluster-secret
  annotations: {{- include "sulfoxide-carbon.annotations" $ | nindent 4 }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/weight: "1"
  labels: {{- include "sulfoxide-carbon.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $v.refreshInterval }}
  secretStoreRef:
    name: {{ $v.store.name }}
    kind: {{ $v.store.kind }}
  target:
    name: {{ $k }}-cluster-secret
    creationPolicy: {{ $v.policy.creation }}
    deletionPolicy: {{ $v.policy.deletion }}
{{/*    template:*/}}
{{/*      metadata:*/}}
{{/*        labels: {{- include "sulfoxide-carbon.labels" $ | nindent 10 }}*/}}
{{/*        annotations: {{- include "sulfoxide-carbon.annotations" $ | nindent 10 }}*/}}
{{/*      data:*/}}
{{/*        BEARER_TOKEN: '{{ `{{ get ((get ( .kubeconfig | fromJson ) "config") | fromJson ) "bearerToken" }}` }}'*/}}
  data:
    - secretKey: "iodine"
      remoteRef:
        key: "vc-{{ $.Values.serviceTree.landscape }}-{{ $k }}-iodine.{{ $k }}"
---
{{- end }}